17.02/bubble sort
IgnatSergeev/forSpbu pull request #33
Opened 2023-02-22 22:49 UTC by IgnatSergeev

2023-02-23 23:42 UTC, victoriafomina requested changes

2023-02-23 23:42 UTC, victoriafomina commented on C#/forSpbu/BubbleSort/Program.cs
> +﻿using System.Runtime.CompilerServices;
Неиспользуемый _using_. Уберите, пожалуйста

2023-02-23 23:42 UTC, victoriafomina commented on C#/forSpbu/BubbleSort/Program.cs
> +namespace BubbleSort
Используйте [file scoped namespaces](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-10.0/file-scoped-namespaces) вместо namespaces с фигурными скобочками

2023-02-23 23:42 UTC, victoriafomina commented on C#/forSpbu/BubbleSort/Program.cs
> +    class Program
Ваш класс - это набор статических методов, его тоже нужно сделать статическим.

Имеет смысл всегда писать модификаторы видимости, например, `public static Program` вместо `static Program`, чтобы при чтении кода у разработчика, который никогда не писал на С#, не возникало лиших вопросов по поводу областей видимости. В целом так код будь чуточку читабельнее

2023-02-23 23:42 UTC, victoriafomina commented on C#/forSpbu/BubbleSort/Program.cs
> +        static bool test()
Методы нужно именовать с заглавной буквы

2023-02-23 23:42 UTC, victoriafomina commented on C#/forSpbu/BubbleSort/Program.cs
> +        }
Класс Program в данном случае должен содержать только метод Main с логикой по запуску вашего кода.

Тесты, пожалуйста, вынесите в отдельный класс

2023-02-23 23:42 UTC, victoriafomina commented on C#/forSpbu/BubbleSort/Program.cs
> +        }
Логику сортировки тоже нужно вынести в отдельный класс

2023-02-23 23:42 UTC, victoriafomina commented on C#/forSpbu/BubbleSort/Program.cs
> +        public static void BubbleSort(int[] array)
Публичный метод - это окошко во внешний мир.
Пользователь может передать сюда null, пустой массив в качестве значений. В таких случаях ваша программа просто упадет. Такого быть не должно. Эти случаи нужно обработать, пользователя стоит уведомить о некорректном вводе

2023-02-23 23:42 UTC, victoriafomina commented on C#/forSpbu/BubbleSort/Program.cs
> +            int[] array = Console.ReadLine().Split().Select(x => int.Parse(x)).ToArray();
Во-первых, `Console.ReadLine` вполне может вернуть _null_, например, при вводе `Ctrl + Z`. А вы не проверяете значение, которое вам возвращается. Можно свалиться с NullPointerException.

Во-вторых, никто не гарантирует, что пользователь именно числа введет. Если он введет, например, букву, то программа упадет при попытке распарсить int. Поэтому стоит использовать не `Int.Parse(...)`, а `Int.TryParse(...)`, результат работы которого можно проверить

2023-02-23 23:42 UTC, victoriafomina commented on C#/forSpbu/BubbleSort/Program.cs
> +                Console.Write(" ");
Это ровно `Console.WriteLine(array[i]);` делает

2023-03-01 11:12 UTC, IgnatSergeev commented on C#/forSpbu/BubbleSort/Program.cs
> +                Console.Write(" ");
Он печатает по элементу на строке, а у меня была цель печатать все элементы через пробел на одной строке

2023-03-01 21:48 UTC, victoriafomina commented on C#/forSpbu/BubbleSort/Program.cs
> +                Console.Write(" ");
> Он печатает по элементу на строке, а у меня была цель печатать все элементы через пробел на одной строке

Тьфу, подумала об одном - написала другое. `Console.Write($"{array[i]} ");` можно

2023-03-02 18:57 UTC, victoriafomina approved these changes

2023-03-02 18:57 UTC, victoriafomina commented on C#/forSpbu/BubbleSort/Program.cs
> +        }
Пользуйтесь [top-level statements](https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/tutorials/top-level-statements)

2023-03-02 18:57 UTC, victoriafomina commented on C#/forSpbu/BubbleSort/Program.cs
> +        int[] array = line.Split().Select(x => int.TryParse(x, out var y) ? y: throw new Exception("Wrong array element")).ToArray();
Используйте _var_ - аналог _auto_ в C++.
Это
```csharp
int[] array = line.Split().Select(x => int.TryParse(x, out var y) ? y: throw new Exception("Wrong array element")).ToArray();
```
можно записать так:
```csharp
var array = line.Split().Select(x => int.TryParse(x, out var y) ? y: throw new Exception("Wrong array element")).ToArray();
```

, где тип левой части будет на самом деле известен компилятору по правой части выражения.

В целом все ок, поэтому зачтено

2023-03-15 14:39 UTC, merged